# config file to load data, change paths if data is located in a different dir 
elliptic_dataset:
  folder: /data/elliptic/
  classes_file: elliptic_txs_classes.csv
  edges_file: elliptic_txs_edgelist.csv
  feats_file: elliptic_txs_features.csv
